# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
