# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_ajax', '0002_auto_20160830_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
