# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-20 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_ajax', '0005_auto_20160905_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['list_order']},
        ),
    ]
